### PR TITLE
Added support for React messages

### PR DESCRIPTION
**Pull request by ghost**
Added support for the slack reactions.add api call.

### CODE REVIEW

**Comment by ghost** [comment]
Sure. In slack, you can add a reaction to any message, via the "add reaction" context menu for a given message, or using the keyboard with a ctrl+shift+\
This adds the functionality to the Bot class, so a responder can add a reaction to a trigger message, and then it would probably return a null response. An example: a responder could be created that performed some action, but instead of sending a response message "okay did it", the responder could just add a :thumbsup: reaction emoticon  to the trigger message.

**Comment by madslyng** [comment]
Okay, that seems good. One comment though. Doesn't it appear to you that a lot of the code is duplicated ? Say() and React() look almost the same.. just wondering if we can improve on that ?

**Comment by ghost** [comment]
Yes, we probably could - but it had different requirements up to the actual
http post.
I'll take a look at it tomorrow, I won't be around a computer tonight.

**Comment by ghost** [comment]
I took a look at the Say() and React() - while similar, there's not much we could do in terms of simplifying them/reducing them. What looks like duplication isn't, since:
- React needs to verify the context has a timestamp
- React needs different items in the values list, namely "timestamp" and "name"

So, aside from the GetChatHubId, which I already broke out into a reusable static method, I think we're as simplified as we can be.
Do you have any other suggestions?

**Comment by jammerware** [comment]
@AndrewArace Thanks for your work on this. As you saw, there's another developer trying to do something similar [over here](https://github.com/jammerware/margiebot/pull/10), so let's work on that angle together. Sorry for being a little slapdash about keeping up with these pull requests. I'm pretty new to collaboration on github. Thanks again for working on this!

**Comment by ghost** [comment]
Understood, that's a better approach, anyway.
:thumbsup: :)

**Pull request closed without merging**
